@bot.command()
async def hack(ctx, member : discord.Member):
    msg = await ctx.send(f"Hacking {member.mention} now...")
    time.sleep(2)
    await msg.edit(content=f"Finding {member.mention}'s E-mail and password...")
    time.sleep(2)
    await msg.edit(content=f"Successfully found {member.mention}'s personal information \n \n**E-Mail:** `{member.name}HasASmallPeen@gmail.com` \n**Password:** `ctrustno1`")
    time.sleep(4)
    await msg.edit(content="Finding IP Address...")
    time.sleep(2)
    await msg.edit(content="**IP Address:** `127.0.0.1:754`")
    time.sleep(2)
    await msg.edit(content="Grabbing Discord Token...")
    time.sleep(1)
    await msg.edit(content="Loading.")
    await msg.edit(content="Loading..")
    await msg.edit(content="Loading...")
    await msg.edit(content="Token Found \n**Token:** `6qrZcUqja7812RVdnEKjpzOL4CvHBFG`")
    time.sleep(2)
    await msg.edit(content=f"Finished hacking {member.mention}")
